In [21]:
import numpy as np
x = np.array([[ 3,  5],
           [ 5,  1],
           [10, 2]])
y = np.array([[72],
           [82],
           [92]])

y

array([[72],
       [82],
       [92]])

In [22]:
x

array([[ 3,  5],
       [ 5,  1],
       [10,  2]])

In [23]:
#ArtificialNeuralNetwork

In [30]:
x = x/np.amax(x, axis=0)
x

array([[ 0.3,  1. ],
       [ 0.5,  0.2],
       [ 1. ,  0.4]])

In [31]:
y = y/np.amax(y, axis=0)
y

array([[ 0.7826087 ],
       [ 0.89130435],
       [ 1.        ]])

In [32]:
y

array([[ 0.7826087 ],
       [ 0.89130435],
       [ 1.        ]])

In [48]:
class Neural_Network(object):
    def __init__(self):
        # HyperParameters
        self.inputLayerSize = 2
        self.outputLayerSize = 1
        self.hiddenLayerSize = 3
        
        
        #Weight (parameters)
        self.W1 = np.random.randn(self.inputLayerSize, \
                               self.hiddenLayerSize)
        self.W2 = np.random.randn(self.hiddenLayerSize, \
                               self.outputLayerSize)
        
    def forward(self, x):
        #Propagate inputs through network
        self.z2 = np.dot(x, self.W1)
        self.a2 = self.sigmoid(self.z2)
        self.z3 = np.dot(self.a2, self.W2)
        yHat = self.sigmoid(self.z3)
        return yHat
    
    def sigmoid(self, z):
        return 1/(1+np.exp(-z))

In [49]:
NN = Neural_Network()

In [52]:
yHat = NN.forward(x)

In [53]:
yHat

array([[ 0.34697537],
       [ 0.30819282],
       [ 0.36339879]])

In [54]:
y

array([[ 0.7826087 ],
       [ 0.89130435],
       [ 1.        ]])